name: Build Dist
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        run: npm ci

      - name: Build Dist
        run: npm run build

      - name: Push to GitHub
        run: |
          git add dist/
          git commit -m "update dist"
          git push origin main
