name: Run tests
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        run: npm ci

      - name: Lint
        run: |
          npm run prettier:check
          npm run lint

      - name: Run tests
        run: |
          npm test
          npm run coverage

      - name: Upload coverage report to codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage/cobertura-coverage.xml

      - name: Write coverage badge
        uses: action-badges/cobertura-coverage-xml-badges@0.1.0
        if: github.ref == 'refs/heads/main'
        with:
          badge-branch: badges
          file-name: coverage.svg
          github-token: '${{ secrets.GITHUB_TOKEN }}'
          coverage-file-name: ./coverage/cobertura-coverage.xml
